name: Credit Score VFL Retraining Pipeline

on:
  workflow_dispatch:

jobs:
  # --------------------------------
  # AUTO LOAN DRIFT DETECTOR + TRAIN
  # --------------------------------
  detect-auto-loan-drift:
    runs-on: ubuntu-latest
    outputs:
      auto_loan_drift_detected: ${{ steps.check.outputs.auto_loan_drift_detected }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Auto Loan Drift Detection
        id: check
        run: |
          result=$(python VFLClientModels/drift_detection_retraining/auto_loans_drift_detector_pipeline.py | tail -n 1)
          echo "$result" >> $GITHUB_OUTPUT

  retrain-auto-loan:
    needs: detect-auto-loan-drift
    if: needs.detect-auto-loan-drift.outputs.auto_loan_drift_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Retrain Auto Loan Model
        run: python VFLClientModels/models/auto_loans_model.py

  # -------------------------------------
  # CREDIT CARD DRIFT DETECTOR + TRAIN
  # -------------------------------------
  detect-credit-card-drift:
    runs-on: ubuntu-latest
    outputs:
      credit_card_drift_detected: ${{ steps.check.outputs.credit_card_drift_detected }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Credit Card Drift Detection
        id: check
        run: |
          result=$(python VFLClientModels/drift_detection_retraining/xgboost_drift_detector_pipeline.py | tail -n 1)
          echo "$result" >> $GITHUB_OUTPUT

  retrain-credit-card:
    needs: detect-credit-card-drift
    if: needs.detect-credit-card-drift.outputs.credit_card_drift_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Retrain Credit Card Model
        run: python VFLClientModels/drift_detection_retraining/pipelinenextstagesimulation.py
        # run: python VFLClientModels/models/credit_card_xgboost_model.py

  # -----------------------------------
  # HOME LOAN DRIFT DETECTOR + TRAIN
  # -----------------------------------
  detect-home-loan-drift:
    runs-on: ubuntu-latest
    outputs:
      home_loan_drift_detected: ${{ steps.check.outputs.home_loan_drift_detected }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Home Loan Drift Detection
        id: check
        run: |
          result=$(python VFLClientModels/drift_detection_retraining/home_loans_drift_detector_pipeline.py | tail -n 1)
          echo "$result" >> $GITHUB_OUTPUT

  retrain-home-loan:
    needs: detect-home-loan-drift
    if: needs.detect-home-loan-drift.outputs.home_loan_drift_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Retrain Home Loan Model
        run: python VFLClientModels/drift_detection_retraining/pipelinenextstagesimulation.py
        # run: python VFLClientModels/models/home_loans_model.py

  # ----------------------------------------
  # DIGITAL SAVINGS DRIFT DETECTOR + TRAIN
  # ----------------------------------------
  detect-digital-savings-drift:
    runs-on: ubuntu-latest
    outputs:
      digital_savings_drift_detected: ${{ steps.check.outputs.digital_savings_drift_detected }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Digital Savings Drift Detection
        id: check
        run: |
          result=$(python VFLClientModels/drift_detection_retraining/digital_savings_drift_detector_pipeline.py | tail -n 1)
          echo "$result" >> $GITHUB_OUTPUT

  retrain-digital-savings:
    needs: detect-digital-savings-drift
    if: needs.detect-digital-savings-drift.outputs.digital_savings_drift_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Retrain Digital Savings Model
        run: python VFLClientModels/models/digital_savings_model.py

  # -------------------------
  # VFL MASTER RETRAINING
  # -------------------------
  retrain-vfl-model:
    needs:
      - detect-auto-loan-drift
      - detect-credit-card-drift
      - detect-home-loan-drift
      - detect-digital-savings-drift
      - retrain-auto-loan
      - retrain-credit-card
      - retrain-home-loan
      - retrain-digital-savings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Always run debug info
        run: |
          echo "Auto Loan Drift: ${{ needs.detect-auto-loan-drift.outputs.auto_loan_drift_detected }}"
          echo "Credit Card Drift: ${{ needs.detect-credit-card-drift.outputs.credit_card_drift_detected }}"
          echo "Home Loan Drift: ${{ needs.detect-home-loan-drift.outputs.home_loan_drift_detected }}"
          echo "Digital Savings Drift: ${{ needs.detect-digital-savings-drift.outputs.digital_savings_drift_detected }}"

      - name: Conditional VFL retraining
        run: |
          echo "Evaluating condition..."
          if [ "${{ needs.detect-auto-loan-drift.outputs.auto_loan_drift_detected }}" = "true" ] ||
             [ "${{ needs.detect-credit-card-drift.outputs.credit_card_drift_detected }}" = "true" ] ||
             [ "${{ needs.detect-home-loan-drift.outputs.home_loan_drift_detected }}" = "true" ] ||
             [ "${{ needs.detect-digital-savings-drift.outputs.digital_savings_drift_detected }}" = "true" ]; then
            echo "Triggering VFL retraining..."
            python VFLClientModels/models/vfl_automl_xgboost_homoenc_dp.py
          else
            echo "No drift detected. Skipping VFL retraining."
          fi
